apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cement-plant-hpa
  namespace: cement-plant-ai
  labels:
    app: cement-plant-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cement-plant-digital-twin
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: cement_plant_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: cement-plant-monitor
  namespace: cement-plant-ai
  labels:
    app: cement-plant-ai
spec:
  selector:
    matchLabels:
      app: cement-plant-ai
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cement-plant-alerts
  namespace: cement-plant-ai
  labels:
    app: cement-plant-ai
spec:
  groups:
  - name: cement-plant.rules
    rules:
    - alert: CementPlantHighCPU
      expr: rate(container_cpu_usage_seconds_total{pod=~"cement-plant-.*"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
        service: cement-plant-ai
      annotations:
        summary: "High CPU usage detected"
        description: "Cement plant AI pod {{ $labels.pod }} has high CPU usage"
    
    - alert: CementPlantHighMemory
      expr: container_memory_usage_bytes{pod=~"cement-plant-.*"} / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: warning
        service: cement-plant-ai
      annotations:
        summary: "High memory usage detected"
        description: "Cement plant AI pod {{ $labels.pod }} has high memory usage"
    
    - alert: CementPlantPodCrashLoop
      expr: rate(kube_pod_container_status_restarts_total{pod=~"cement-plant-.*"}[15m]) > 0
      for: 5m
      labels:
        severity: critical
        service: cement-plant-ai
      annotations:
        summary: "Pod crash loop detected"
        description: "Cement plant AI pod {{ $labels.pod }} is in crash loop"
    
    - alert: CementPlantServiceDown
      expr: up{job="cement-plant-service"} == 0
      for: 1m
      labels:
        severity: critical
        service: cement-plant-ai
      annotations:
        summary: "Cement plant service is down"
        description: "Cement plant AI service is not responding"
---
apiVersion: v1
kind: NetworkPolicy
metadata:
  name: cement-plant-netpol
  namespace: cement-plant-ai
spec:
  podSelector:
    matchLabels:
      app: cement-plant-ai
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app: cement-plant-ai
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 9090
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS for Google Cloud APIs
    - protocol: TCP
      port: 80   # HTTP for Google Cloud APIs
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cement-plant-backup
  namespace: cement-plant-ai
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cement-plant-sa
          containers:
          - name: backup
            image: gcr.io/cement-ai-opt-38517/cement-plant-backup:latest
            env:
            - name: CEMENT_GCP_PROJECT
              value: "cement-ai-opt-38517"
            - name: CEMENT_BQ_DATASET
              value: "cement_analytics"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
